# Generated by Django 3.2.6 on 2023-09-17 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_title', models.CharField(max_length=200)),
                ('not_body', models.TextField()),
                ('not_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('not_fk_user', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
